import { HeaderIconItem } from "@/types/data";

export const iconOptions = {
  flowers: [
    "/flowers/regular-shape/1.svg",
    "/flowers/regular-shape/1-1.svg",
    "/flowers/regular-shape/1-2.svg",
    "/flowers/regular-shape/2.svg",
    "/flowers/regular-shape/2-1.svg",
    "/flowers/regular-shape/3.svg",
    "/flowers/regular-shape/4.svg",
    "/flowers/regular-shape/5.svg",
    "/flowers/regular-shape/6.svg",
    "/flowers/regular-shape/7.svg",
  ],
  glass: [
    "/glass/regular-shape/png.svg",
    "/glass/regular-shape/png-1.svg",
    "/glass/regular-shape/png-2.svg",
    "/glass/regular-shape/png-3.svg",
    "/glass/regular-shape/png-4.svg",
    "/glass/regular-shape/png-5.svg",
    "/glass/regular-shape/png-6.svg",
    "/glass/regular-shape/png-7.svg",
    "/glass/regular-shape/png-8.svg",
    "/glass/regular-shape/png-9.svg",
  ],
  sticker: [
    "/stickers/regular-shape/100.svg",
    "/stickers/regular-shape/Airplane.svg",
    "/stickers/regular-shape/Apple.svg",
    "/stickers/regular-shape/April.svg",
    "/stickers/regular-shape/Ball.svg",
    "/stickers/regular-shape/Bee.svg",
    "/stickers/regular-shape/Book.svg",
    "/stickers/regular-shape/Camera.svg",
    "/stickers/regular-shape/Crown.svg",
    "/stickers/regular-shape/Flower 1.svg",
  ],
  shapes: [
    "/shapes/regular-shape/A1.svg",
    "/shapes/regular-shape/A2.svg",
    "/shapes/regular-shape/A3.svg",
    "/shapes/regular-shape/A4.svg",
    "/shapes/regular-shape/B1.svg",
    "/shapes/regular-shape/B2.svg",
    "/shapes/regular-shape/B3.svg",
    "/shapes/regular-shape/B4.svg",
    "/shapes/regular-shape/C1.svg",
    "/shapes/regular-shape/C2.svg",
  ],
} as const;

export const initialHeaderIcons: HeaderIconItem[] = [
  {
    src: "/assets/preview1.svg",
    alt: "first preview image",
    width: 66,
    height: 90,
    note: "",
  },
  {
    src: "/assets/preview2.svg",
    alt: "flower",
    width: 80,
    height: 80,
    note: "",
  },
  {
    src: "/assets/preview3.svg",
    alt: "third preview image",
    width: 89,
    height: 76,
    note: "",
  },
  {
    src: "/assets/preview4.svg",
    alt: "fourth preview image",
    width: 90,
    height: 90,
    note: "",
  },
  {
    src: "/assets/preview7.svg",
    alt: "fifth preview image",
    width: 90,
    height: 88,
    note: "",
  },
  {
    src: "/assets/preview6.svg",
    alt: "sixth preview image",
    width: 76,
    height: 76,
    note: "",
  },
];